[package]
name = "proc-macro-tools"
version = "0.1.0"
authors = ["Michael Micucci <9975355+kitsuneninetails@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
regex = "*"
